export type CueType = "note" | "camera" | "pause";

export type ScriptBlock = {
  id: string;
  sectionId: string;
  text: string;
  triggerStepId?: string;
  cue?: string;
  cueType?: CueType;
  emphasis?: boolean;
};

export type ScriptSection = {
  id: string;
  number: string;
  title: string;
  firstStepId: string;
};

export const scriptSections: ScriptSection[] = [
  { id: "opening", number: "00", title: "Opening", firstStepId: "intro-title" },
  { id: "find", number: "01", title: "Find Me", firstStepId: "find-start" },
  { id: "orient", number: "02", title: "Orient Me", firstStepId: "orient-start" },
  { id: "read", number: "03", title: "Read Me", firstStepId: "read-start" },
  { id: "repair", number: "04", title: "Repair Me", firstStepId: "repair-start" },
  { id: "decode", number: "05", title: "Decode Me", firstStepId: "decode-camera" },
  { id: "destination", number: "06", title: "Destination", firstStepId: "destination-qr" },
  { id: "security", number: "07", title: "Which One Do You Trust?", firstStepId: "security-start" },
  { id: "conclusion", number: "08", title: "Conclusion", firstStepId: "final-message" }
];

export const scriptBlocks: ScriptBlock[] = [
  { id: "title", sectionId: "opening", text: "Inside the Code", triggerStepId: "intro-title", emphasis: true },
  { id: "sps", sectionId: "opening", text: "SPS: To explain how QR codes work and demonstrate how sophisticated technology can make a complicated process remarkably simple.", cue: "Purpose statement", cueType: "note" },
  { id: "open-1", sectionId: "opening", text: "Thank you, Mr Toastmaster, Good evening Mr Director and Fellow Spokesmen...", cue: "Look up and settle", cueType: "camera" },
  { id: "open-2", sectionId: "opening", text: "We've all seen this before.", triggerStepId: "intro-qr" },
  { id: "open-3", sectionId: "opening", text: "You'll find it on restaurant tables." },
  { id: "open-4", sectionId: "opening", text: "On tickets." },
  { id: "open-5", sectionId: "opening", text: "On packaging." },
  { id: "open-6", sectionId: "opening", text: "On advertisements." },
  { id: "open-7", sectionId: "opening", text: "And most of us know exactly what we're supposed to do when we see one." },
  { id: "open-8", sectionId: "opening", text: "We take out our phones...", triggerStepId: "intro-detected" },
  { id: "open-9", sectionId: "opening", text: "point the camera at it..." },
  { id: "open-10", sectionId: "opening", text: "and within seconds, something happens." },
  { id: "open-11", sectionId: "opening", text: "A menu appears." },
  { id: "open-12", sectionId: "opening", text: "A website opens." },
  { id: "open-13", sectionId: "opening", text: "A payment page loads." },
  { id: "open-14", sectionId: "opening", text: "Information that looks completely meaningless to us suddenly becomes information our phone can understand." },
  { id: "open-15", sectionId: "opening", text: "But have you ever stopped to think about what actually happened during those few seconds?", cue: "Pause", cueType: "pause" },
  { id: "open-16", sectionId: "opening", text: "Because when we look at this..." },
  { id: "open-17", sectionId: "opening", text: "we see a strange collection of black and white squares." },
  { id: "open-18", sectionId: "opening", text: "Your phone sees something completely different." },
  { id: "open-19", sectionId: "opening", text: "So tonight, Spokesmen, rather than simply looking at a QR code...", triggerStepId: "intro-enter" },
  { id: "open-20", sectionId: "opening", text: "let's step inside one." },
  { id: "open-21", sectionId: "opening", text: "If you have your phone nearby, go ahead and scan the code on the screen.", triggerStepId: "intro-detected", cue: "Allow 10 seconds for scan", cueType: "pause" },
  { id: "open-22", sectionId: "opening", text: "Keep that website open. You can scroll through it during the presentation, and there is a small game at the end of the website you can later enjoy" },
  { id: "open-23", sectionId: "opening", text: "Now, obviously, we're not literally going to travel through a QR code." },
  { id: "open-24", sectionId: "opening", text: "But let's use it to understand what your phone just did." },
  { id: "open-25", sectionId: "opening", text: "Because the process began before the website ever opened." },

  { id: "find-1", sectionId: "find", text: "The first problem your phone had to solve was actually quite simple:", triggerStepId: "intro-find" },
  { id: "find-2", sectionId: "find", text: "Where is the QR code?", triggerStepId: "find-start", emphasis: true },
  { id: "find-3", sectionId: "find", text: "Take a look at these three large squares." },
  { id: "find-4", sectionId: "find", text: "One here.", triggerStepId: "find-top-left" },
  { id: "find-5", sectionId: "find", text: "One here.", triggerStepId: "find-top-right" },
  { id: "find-6", sectionId: "find", text: "And one here.", triggerStepId: "find-bottom-left" },
  { id: "find-7", sectionId: "find", text: "These are called finder patterns." },
  { id: "find-8", sectionId: "find", text: "They help the scanner locate the QR code within the image." },
  { id: "find-9", sectionId: "find", text: "Think about how casually we actually scan these things." },
  { id: "find-10", sectionId: "find", text: "You don't carefully line up your phone." },
  { id: "find-11", sectionId: "find", text: "You don't measure the distance." },
  { id: "find-12", sectionId: "find", text: "You don't tell your camera:" },
  { id: "find-13", sectionId: "find", text: "\"QR code - approximately three centimetres to the left.\"" },
  { id: "find-14", sectionId: "find", text: "You just point your phone somewhere in its general direction." },
  { id: "find-15", sectionId: "find", text: "And yet...", cue: "Pause", cueType: "pause" },
  { id: "find-16", sectionId: "find", text: "it finds it.", triggerStepId: "find-complete", emphasis: true },
  { id: "find-17", sectionId: "find", text: "Those distinctive patterns help the scanner recognize and locate the code." },
  { id: "find-18", sectionId: "find", text: "But finding it creates another problem." },

  { id: "orient-1", sectionId: "orient", text: "What happens if the QR code looks like this?", triggerStepId: "orient-90" },
  { id: "orient-2", sectionId: "orient", text: "Or this?", triggerStepId: "orient-180" },
  { id: "orient-3", sectionId: "orient", text: "You can still scan it." },
  { id: "orient-4", sectionId: "orient", text: "You don't have to turn your phone upside down." },
  { id: "orient-5", sectionId: "orient", text: "The structure of the QR code helps the scanner determine its orientation." },
  { id: "orient-6", sectionId: "orient", text: "Those finder patterns provide reference points that help the scanner understand how the code is positioned." },
  { id: "orient-7", sectionId: "orient", text: "And once it has figured that out...", triggerStepId: "orient-lock" },
  { id: "orient-8", sectionId: "orient", text: "it can begin interpreting the actual information." },

  { id: "read-1", sectionId: "read", text: "Now we need to go deeper.", triggerStepId: "read-zoom" },
  { id: "read-2", sectionId: "read", text: "What looks like one image from a distance is actually made up of many individual squares." },
  { id: "read-3", sectionId: "read", text: "These are called modules." },
  { id: "read-4", sectionId: "read", text: "And they're not random decoration." },
  { id: "read-5", sectionId: "read", text: "The arrangement forms part of a carefully defined structure that represents encoded digital information.", triggerStepId: "read-data" },
  { id: "read-6", sectionId: "read", text: "The scanner analyses that structure..." },
  { id: "read-7", sectionId: "read", text: "interprets the encoded data...", triggerStepId: "read-characters" },
  { id: "read-8", sectionId: "read", text: "and eventually turns it into something useful." },
  { id: "read-9", sectionId: "read", text: "That could be text." },
  { id: "read-10", sectionId: "read", text: "Numbers." },
  { id: "read-11", sectionId: "read", text: "Contact information." },
  { id: "read-12", sectionId: "read", text: "And very commonly..." },
  { id: "read-13", sectionId: "read", text: "a website address.", triggerStepId: "read-url", emphasis: true },
  { id: "read-14", sectionId: "read", text: "So somewhere within the information represented by that QR code was an address telling your phone where it could go." },
  { id: "read-15", sectionId: "read", text: "But now we have an interesting problem." },
  { id: "read-16", sectionId: "read", text: "If the pattern contains information..." },
  { id: "read-17", sectionId: "read", text: "what happens when I do this?", triggerStepId: "repair-start" },

  { id: "repair-1", sectionId: "repair", text: "Here's our QR code.", triggerStepId: "repair-start" },
  { id: "repair-2", sectionId: "repair", text: "Let's damage it.", cue: "QR damage", cueType: "note" },
  { id: "repair-3", sectionId: "repair", text: "Well..." },
  { id: "repair-4", sectionId: "repair", text: "that's not good." },
  { id: "repair-5", sectionId: "repair", text: "Part of our code is now missing.", triggerStepId: "repair-missing" },
  { id: "repair-6", sectionId: "repair", text: "So surely the whole thing should be useless." },
  { id: "repair-7", sectionId: "repair", text: "Not necessarily.", emphasis: true },
  { id: "repair-8", sectionId: "repair", text: "QR codes can contain something called error-correction information.", triggerStepId: "repair-error-correction" },
  { id: "repair-9", sectionId: "repair", text: "That can allow the scanner, within limits, to recover from some missing or damaged information." },
  { id: "repair-10", sectionId: "repair", text: "This is one reason you've probably seen QR codes that are scratched..." },
  { id: "repair-11", sectionId: "repair", text: "dirty..." },
  { id: "repair-12", sectionId: "repair", text: "partially obscured..." },
  { id: "repair-13", sectionId: "repair", text: "or even designed with a logo covering part of them..." },
  { id: "repair-14", sectionId: "repair", text: "and your phone can sometimes still scan them successfully.", triggerStepId: "repair-recovered" },
  { id: "repair-15", sectionId: "repair", text: "Now, that doesn't mean we can destroy half the code and expect miracles." },
  { id: "repair-16", sectionId: "repair", text: "How much damage can be tolerated depends on how the QR code was created and the level of error correction being used." },
  { id: "repair-17", sectionId: "repair", text: "But the principle is fascinating." },
  { id: "repair-18", sectionId: "repair", text: "Some information can become unavailable..." },
  { id: "repair-19", sectionId: "repair", text: "and yet enough additional information may remain to recover what's needed.", triggerStepId: "repair-complete" },
  { id: "repair-20", sectionId: "repair", text: "And now our scanner has everything it needs." },

  { id: "decode-1", sectionId: "decode", text: "Let's put the journey together.", triggerStepId: "decode-camera" },
  { id: "decode-2", sectionId: "decode", text: "First...", cue: "Build the pipeline", cueType: "note" },
  { id: "decode-3", sectionId: "decode", text: "the camera captures the image." },
  { id: "decode-4", sectionId: "decode", text: "The software detects the QR code.", triggerStepId: "decode-detect" },
  { id: "decode-5", sectionId: "decode", text: "It determines its orientation.", triggerStepId: "decode-orient" },
  { id: "decode-6", sectionId: "decode", text: "It reads the encoded structure.", triggerStepId: "decode-read" },
  { id: "decode-7", sectionId: "decode", text: "It handles errors where possible.", triggerStepId: "decode-correct" },
  { id: "decode-8", sectionId: "decode", text: "And finally..." },
  { id: "decode-9", sectionId: "decode", text: "it decodes the information.", triggerStepId: "decode-final" },
  { id: "decode-10", sectionId: "decode", text: "And in the QR code you scanned at the beginning..." },
  { id: "decode-11", sectionId: "decode", text: "that information included something extremely important." },
  { id: "decode-12", sectionId: "decode", text: "An address.", triggerStepId: "decode-url", emphasis: true },

  { id: "destination-1", sectionId: "destination", text: "The QR code itself isn't magically a website.", triggerStepId: "destination-qr" },
  { id: "destination-2", sectionId: "destination", text: "It contains information that your phone can decode and use.", triggerStepId: "destination-url" },
  { id: "destination-3", sectionId: "destination", text: "And when that information contains a web address...", triggerStepId: "destination-address" },
  { id: "destination-4", sectionId: "destination", text: "your phone can offer to take you there.", triggerStepId: "destination-website" },
  { id: "destination-5", sectionId: "destination", text: "Which means the website sitting on your phone right now..." },
  { id: "destination-6", sectionId: "destination", text: "started here.", triggerStepId: "destination-info" },
  { id: "destination-7", sectionId: "destination", text: "Passed through all of this..." },
  { id: "destination-8", sectionId: "destination", text: "and ended..." },
  { id: "destination-9", sectionId: "destination", text: "here.", triggerStepId: "destination-here", emphasis: true },
  { id: "destination-10", sectionId: "destination", text: "All within a few seconds." },
  { id: "destination-11", sectionId: "destination", text: "But there's one more thing about QR codes that I think is worth understanding." },

  { id: "security-1", sectionId: "security", text: "Take a look at these two QR codes.", triggerStepId: "security-start" },
  { id: "security-2", sectionId: "security", text: "Which one do you trust?", cue: "Look at audience", cueType: "camera" },
  { id: "security-3", sectionId: "security", text: "Can you tell me where this one goes?", triggerStepId: "security-a" },
  { id: "security-4", sectionId: "security", text: "What about this one?", triggerStepId: "security-b" },
  { id: "security-5", sectionId: "security", text: "Probably not." },
  { id: "security-6", sectionId: "security", text: "Because although our phones can interpret these patterns..." },
  { id: "security-7", sectionId: "security", text: "we can't." },
  { id: "security-8", sectionId: "security", text: "To us, they both look like collections of black and white squares." },
  { id: "security-9", sectionId: "security", text: "One might take you to a restaurant menu." },
  { id: "security-10", sectionId: "security", text: "The other could take you somewhere completely different." },
  { id: "security-11", sectionId: "security", text: "And simply looking at the pattern doesn't reliably tell you which is which." },
  { id: "security-12", sectionId: "security", text: "So there's also a practical lesson here." },
  { id: "security-13", sectionId: "security", text: "Treat QR codes much like you would any other link.", triggerStepId: "security-reveal", emphasis: true },
  { id: "security-14", sectionId: "security", text: "Consider where the code came from before opening it.", triggerStepId: "security-check" },
  { id: "security-15", sectionId: "security", text: "Technology can make something incredibly easy to use." },
  { id: "security-16", sectionId: "security", text: "But easy doesn't mean we should stop thinking." },

  { id: "conclusion-1", sectionId: "conclusion", text: "Spokesmen...", triggerStepId: "final-message", cue: "Look at camera", cueType: "camera" },
  { id: "conclusion-2", sectionId: "conclusion", text: "A few minutes ago, we started with this." },
  { id: "conclusion-3", sectionId: "conclusion", text: "A collection of black and white squares." },
  { id: "conclusion-4", sectionId: "conclusion", text: "We couldn't read it." },
  { id: "conclusion-5", sectionId: "conclusion", text: "We couldn't tell what information it contained." },
  { id: "conclusion-6", sectionId: "conclusion", text: "And we couldn't determine where it would take us simply by looking at it." },
  { id: "conclusion-7", sectionId: "conclusion", text: "But now we know what's happening beneath the surface." },
  { id: "conclusion-8", sectionId: "conclusion", text: "Your phone has to..." },
  { id: "conclusion-9", sectionId: "conclusion", text: "find the code.", triggerStepId: "final-find" },
  { id: "conclusion-10", sectionId: "conclusion", text: "Determine its orientation.", triggerStepId: "final-orient" },
  { id: "conclusion-11", sectionId: "conclusion", text: "Interpret its structure.", triggerStepId: "final-read" },
  { id: "conclusion-12", sectionId: "conclusion", text: "Handle errors where possible.", triggerStepId: "final-repair" },
  { id: "conclusion-13", sectionId: "conclusion", text: "Decode the information.", triggerStepId: "final-decode" },
  { id: "conclusion-14", sectionId: "conclusion", text: "And finally..." },
  { id: "conclusion-15", sectionId: "conclusion", text: "use it.", triggerStepId: "final-open" },
  { id: "conclusion-16", sectionId: "conclusion", text: "All of that..." },
  { id: "conclusion-17", sectionId: "conclusion", text: "so that we can do this." },
  { id: "conclusion-18", sectionId: "conclusion", text: "Point." },
  { id: "conclusion-19", sectionId: "conclusion", text: "Scan." },
  { id: "conclusion-20", sectionId: "conclusion", text: "Open." },
  { id: "conclusion-21", sectionId: "conclusion", text: "Something that requires almost no technical knowledge from the person using it is actually supported by a remarkably sophisticated system underneath.", triggerStepId: "final-simple" },
  { id: "conclusion-22", sectionId: "conclusion", text: "And perhaps that's one of the marks of really effective technology." },
  { id: "conclusion-23", sectionId: "conclusion", text: "It doesn't necessarily make the world less complicated." },
  { id: "conclusion-24", sectionId: "conclusion", text: "It makes the complication easier for us to handle." },
  { id: "conclusion-25", sectionId: "conclusion", text: "So the next time you see one of these strange collections of black and white squares...", triggerStepId: "final-title" },
  { id: "conclusion-26", sectionId: "conclusion", text: "remember:" },
  { id: "conclusion-27", sectionId: "conclusion", text: "there's much more inside that little square than meets the eye.", triggerStepId: "final-qr", emphasis: true },
  { id: "conclusion-28", sectionId: "conclusion", text: "Thank you.", cue: "Pause, then close", cueType: "pause" }
];
